import {
  ApplicationConfig,
  importProvidersFrom,
  provideBrowserGlobalErrorListeners,
  provideZonelessChangeDetection,
} from '@angular/core';
import { provideRouter } from '@angular/router';
import {
  AlertCircle,
  ArrowRight,
  Brain,
  Briefcase,
  Calendar,
  CheckCircle,
  CircleDot,
  Clock,
  Code,
  Compass,
  Cpu,
  Database,
  Download,
  ExternalLink,
  Eye,
  EyeOff,
  FileText,
  FlaskConical,
  Github,
  Globe,
  Heart,
  Lightbulb,
  Linkedin,
  LucideAngularModule,
  Mail,
  MapPin,
  Medal,
  Menu,
  Moon,
  Phone,
  Send,
  Shield,
  Sparkles,
  Sun,
  Target,
  Twitter,
  Users,
  Wrench,
  X,
  Zap,
} from 'lucide-angular';

import { routes } from './app.routes';
import { provideClientHydration, withEventReplay } from '@angular/platform-browser';

export const appConfig: ApplicationConfig = {
  providers: [
    provideBrowserGlobalErrorListeners(),
    provideZonelessChangeDetection(),
    provideRouter(routes),
    provideClientHydration(withEventReplay()),
    importProvidersFrom(
      LucideAngularModule.pick({
        AlertCircle,
        ArrowRight,
        Brain,
        Briefcase,
        Calendar,
        CheckCircle,
        CircleDot,
        Clock,
        Code,
        Compass,
        Cpu,
        Database,
        Download,
        ExternalLink,
        Eye,
        EyeOff,
        FileText,
        FlaskConical,
        Github,
        Globe,
        Heart,
        Lightbulb,
        Linkedin,
        Mail,
        MapPin,
        Medal,
        Menu,
        Moon,
        Phone,
        Send,
        Shield,
        Sparkles,
        Sun,
        Target,
        Twitter,
        Users,
        Wrench,
        X,
        Zap,
      }),
    ),
  ],
};
